### ISSUE TITLE
Code editor Styles not working 

### ISSUE THREAD

**Issue by bhatganeshdarshan** [bhatganeshdarshan/codeZ#1]
Styles for the monaco-code -editor not being applied properly 

![Screenshot from 2024-10-08 08-56-15](https://github.com/user-attachments/assets/586d4845-652a-44cc-a3a9-c15d720312cc)
![Screenshot from 2024-10-08 08-56-39](https://github.com/user-attachments/assets/f610ecbe-af68-4b14-8841-408eb14c5f7d)

**Comment by LakshmiSowmya04** [comment]
I'm on it
